import { NextRequest, NextResponse } from "next/server"

async function getGeneralToken() {
  return fetch("https://auth.roblox.com/v2/logout", {
    method: "POST",
    headers: {
      Cookie: `.ROBLOSECURITY=${process.env.ROBLOX_COOKIE};`,
      "Content-Type": "application/json",
    },
    credentials: "include",
    redirect: "error",
  })
    .then((res) => {
      return res.headers.get("x-csrf-token")
    })
    .catch((err) => {
      console.log("Unable to get XCSRF Token: " + err)
      return err
    })
}

const token = await getGeneralToken()

async function createDevProduct(
  universeId: number | string,
  name: string,
  description: string,
  priceInRobux: number | string
) {
  console.log(
    `https://apis.roblox.com/developer-products/v1/universes/${universeId}/developerproducts?name=${name}&description=${description}&priceInRobux=${priceInRobux}`
  )
  return fetch(
    `https://apis.roblox.com/developer-products/v1/universes/${universeId}/developerproducts?name=${name}&description=${description}&priceInRobux=${priceInRobux}`,
    {
      method: "POST",
      headers: {
        Cookie: `.ROBLOSECURITY=${process.env.ROBLOX_COOKIE};`,
        "Content-Type": "application/json",
        "X-CSRF-TOKEN": token,
      },
      credentials: "include",
      redirect: "error",
    }
  )
    .then(async (res) => await res.json())
    .then((res) => {
      return NextResponse.json({
        success: true,
        ...res,
      })
    })
    .catch(() => {
      return NextResponse.json(
        {
          success: false,
          error:
            "Could not create developer product. Reasons for this could be: Cookie is not inside the region; Cookie is invalid",
        },
        { status: 500 }
      )
    })
}

export async function GET(request: NextRequest) {
  const priceInRobux = request.nextUrl.searchParams.get("priceInRobux")
  const name = request.nextUrl.searchParams.get("name") ?? crypto.randomUUID()
  const universeId =
    request.nextUrl.searchParams.get("universeId") ?? 2889709413
  const description =
    request.nextUrl.searchParams.get("description") ??
    `Generated by API Endpoint at ${new Date().toISOString().slice(0, 10)}`

  try {
    if (!priceInRobux) {
      return NextResponse.json(
        {
          success: false,
          error: "No priceInRobux provided",
        },
        { status: 400 }
      )
    }
    return await createDevProduct(universeId, name, description, priceInRobux)
  } catch (error) {
    console.log("An error occurred: " + error)
    return NextResponse.json(
      {
        success: false,
        error: "An unknown error occurred" + error,
      },
      { status: 500 }
    )
  }
}
